apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluedeployment
spec:
  replicas: 5
  selector: 
    matchLabels:
      app: webapp
      version: blue 
  template:
    metadata:
      labels:
        app: webapp
        version: blue
    spec:
      containers:
      - name: webapp
        image: rdiazconcha/ckad-webapp-blue:latest
        ports:
        - containerPort: 80    