apiVersion: v1
kind: Service
metadata:
  name: bluegreenservice
spec:
  selector:
    app: webapp
    version: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer